### ISSUE TITLE
It seems that “pretrained weight” file is the same as “re-id network” file.

### ISSUE THREAD

**Issue by ChangeXuan** [yt4766269/TextureGeneration#1]
Hello, thank you for sharing the code. But I found that it seems that file **[pretrained weight](https://drive.google.com/file/d/1XM1bXm029xVJy2sek1Bun96fTACo7c_Q/view)** is the same as file **[re-id network](https://drive.google.com/file/d/1XM1bXm029xVJy2sek1Bun96fTACo7c_Q/view)**. I care about it because I feel they should be different documents. I look forward to your reply. Thank you.

**Comment by jianwang-mpi** [comment]
I am pretty sorry for this mistake and my late response. I have corrected the link to re-id network in readme.md. Is it correct now?

**Comment by ChangeXuan** [comment]
Now the link is correct, thanks for your reply.
