### ISSUE TITLE
UNet texture generator

### ISSUE THREAD

**Issue by jinx2018** [yt4766269/TextureGeneration#2]
Hi, I'm a little confused about  **How to train unet texture generator to obtain the full texture map since Market dataset doesn't contain groundtruth texrure map** ? 

Thanks.

**Comment by jianwang-mpi** [comment]
Hi,

Sorry for replying late.

Our method does not need the ground truth full texture map to train the model. You can check this out from our paper:

Re-Identification Supervised Texture Generation

Sincerely,

Jian

**Comment by jinx2018** [comment]
Thanks for your reply!  Now, I came to catch the insight of this paper: In some sense, doesn't it mean that **it just equal the texture generation supervised loss with the Re-ID loss and face loss**?

**Comment by jianwang-mpi** [comment]
Somehow.
