### ISSUE TITLE
Pretrained re-id network is not available

### ISSUE THREAD

**Issue by tinatiansjz** [yt4766269/TextureGeneration#3]
Hello, thanks for sharing the code! But it seems that **pretrained re-id network** is no longer accessible.
I'll appreciate for your response.

![image](https://user-images.githubusercontent.com/27990189/82299528-37737f80-99e8-11ea-9481-de4d1a77ee05.png)

**Comment by jianwang-mpi** [comment]
Hello Tina,

I have restored the pretrained re-id network.

I mistakenly deleted the pretrained network and I am sorry for my late response.

Sincerely,

Jian Wang
