### ISSUE TITLE
Pretrained re-id network is not available again

### ISSUE THREAD

**Issue by zhaofang0627** [yt4766269/TextureGeneration#5]
Hi, thanks for sharing your work! It is great! However, I notice that the pretrained [re-id network](https://drive.google.com/open?id=1Kd4AraJ_uDSHLLE4xu9nMI7MPvbAqj2B) is not available again. Could you kindly restore it? Thank you!

**Comment by jianwang-mpi** [comment]
I accidentally removed them from google drive. Now they should have been restored.

**Comment by zhaofang0627** [comment]
Thanks for your reply! It now works.
